### ISSUE TITLE
Support linking to Python projects from microbit.org

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#237]
## Description

The V2 editor supports specifying project content on the URL (subject to size limits). 

This is used to allow microbit.org projects to be opened in the Python editor via pre-generated URLs.

We should support an equivalent URL-based protocol. There are probably practical benefits to matching V2's URL format exactly.

## Todo

- [ ] Agree any limitations, e.g. still just main.py contents? Some overlap with #236 but potentially different conclusions
    - Implemented exactly as per V2, so it's the name and main.py contents.
- [x] Implement in the editor
- [x] Demo of microbit.org linking to V3 but leave change for some future date
    - Demo branch: http://python-alpha.next-review.microbit.org.s3-website-eu-west-1.amazonaws.com/

## Conclusion

...

**Comment by microbit-matt-hillsdon** [comment]
Reopening this #266 is really just the minimum here and we should agree whether to do anything further.

**Comment by microbit-matt-hillsdon** [comment]
This is fine for launch except for #536 which is tracked separately. Closing.
